defaults: &defaults
  academic_year: 2015
  school_name: Weston High School
  dept_name:  Math Department
  past_assts_num: 5
  cutoff:
    hour: 19
    minute: 30
  last_block: H
  max_occurrences: 5
  occurrences:
    - 1
    - 2
    - 3
    - 4
    - 5
  blocks:
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
  credits:
    - 5.0
    - 2.5
  start_year: 2011
  first_year: 2003

development:
  <<: *defaults
  
test:
  <<: *defaults
  
production:
  <<: *defaults
