defaults: &defaults
  academic_year: 2012
  school_name: Weston High School
  dept_name:  Math Department
  past_assts_num: 5
  cutoff:
    hour: 15
    minute: 0
  start_year: 2011
  last_block: H
  num_occurrences: 5
  occurrences:
    - 1
    - 2
    - 3
    - 4
    - 5
  blocks:
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H

development:
  <<: *defaults
  
test:
  <<: *defaults
  
production:
  <<: *defaults
