#
# Format:
# 
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: in-depth
  stack: cedar
  tag: production/*
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-12345678-1"
  addons:
    - mongolab:starter
    - scheduler:standard
    - memcachier:5mb

staging:
  stack: cedar
  app: in-depth-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
  addons:
    - mongolab:starter
    - scheduler:standard
    - memcachier:5mb

testing:
  stack: cedar
  app: in-depth-testing
  config: *default
  addons:
    - mongolab:starter
    - scheduler:standard
    - memcachier:5mb

viewing:
  stack: cedar
  app: in-depth-viewing
  config: *default
  addons:
    - mongolab:starter
    - scheduler:standard
    - memcachier:5mb

demo: 
  stack: cedar
  app: in-depth-demo
  config: *default
  addons:
    - mongolab:starter
    - scheduler:standard
    - memcachier:5mb
