#
# Format:
# 
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: depthcharge
  stack: cedar
  tag: production/*
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-12345678-1"
  addons:
    - memcache:5mb
    - mongolab:starter
    - scheduler:standard
    - "blitz:250"
    - iron_mq:rust

staging:
  stack: cedar
  app: depthcharge-staging
  tag: staging/*
  config: &default
    BUNDLE_WITHOUT: "development:test"
  addons:
    - memcache:5mb
    - mongolab:starter
    - scheduler:standard
    - "blitz:250"
    - iron_mq:rust

testing:
  stack: cedar
  app: depthcharge-testing
  tag: dev/*
  config: *default
  addons:
    - mongolab:starter
    - scheduler:standard
    - "blitz:250"
    - iron_mq:rust

demo: 
  app: depthcharge-demo
  config: *default
  addons:
    - mongolab:starter
