development:
  sessions:
    default:
      database: depth_charge_development
      hosts:
        - localhost:27017
      options:
        safe: true
        identity_map_enabled: true

test:
  sessions:
    default:
      database: depth_charge_test
      hosts:
        - localhost:27017
      options:
         safe: true
         identity_map_enabled: true
         
# set these environment variables on your prod server
production:
  sessions:
    default: 
      host: <%= ENV['MONGOID_HOST'] %>
      port: <%= ENV['MONGOID_PORT'] %>
      username: <%= ENV['MONGOID_USERNAME'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
      database: <%= ENV['MONGOID_DATABASE'] %>
      options:
         safe: true
         identity_map_enabled: true
      # slaves:
      #   - host: slave1.local
      #     port: 27018
      #   - host: slave2.local
      #     port: 27019
