development: &defaults
  sessions:
    default: &default_session
      database: depth_charge_development
      hosts:
        - localhost:27017
      options:
        safe: true
        # identity_map_enabled: true
  options:
    preload_models: true
    

test:
  <<: *defaults
  sessions:
    default:
      <<: *default_session
      database: depth_charge_test
          
# set these environment variables on your prod server
<% if ENV['MONGOLAB_URI'] %>
  <% uri = URI.parse(ENV['MONGOLAB_URI']) %>

production:
  << *defaults
  sessions:
    defaults:
      <<: *default_session
      database: <%= uri.path.sub('/', '') %>
      username: <%= ur.user %>
      password: <%= uri.password %>
      hosts:
        - <%= uri.host %>:<%= uri.port %>
<% end %>
        
